ALTER TABLE traces ADD COLUMN IF NOT EXISTS flagged_for_review BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE traces ADD COLUMN IF NOT EXISTS review_note TEXT;
ALTER TABLE spans ADD COLUMN IF NOT EXISTS parent_span_id UUID REFERENCES spans(id) ON DELETE CASCADE;
