ALTER TABLE scorers ADD COLUMN IF NOT EXISTS run_online BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE alert_rules ADD COLUMN IF NOT EXISTS webhook_url TEXT;
ALTER TABLE alert_rules ADD COLUMN IF NOT EXISTS last_notified_at TIMESTAMPTZ;
